### ISSUE TITLE
unexpected error found

### ISSUE THREAD

**Issue by rtang03** [rtang03/fabric-es#226]
{
    "log": "2021-09-15T20:30:39+08:00 [error]: :x: fail to mergeEntity, {\"status\":\"ERROR\",\"data\":null,\"error\":{\"message\":\"[Project] Merge Entity Error, [{\\\"message\\\":\\\"fail to reduce, DataRequest:d6463eb6-4be1-4258-80ed-46845888a225:20210915123037330\\\",\\\"stack\\\":\\\"Error: fail to reduce, DataRequest:d6463eb6-4be1-4258-80ed-46845888a225:20210915123037330\\\\n    at Object.mergeEntity (/home/app/node_modules/@fabric-es/fabric-cqrs/dist/queryHandler/createQueryDatabase.js:225:30)\\\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\\"}]\",\"stack\":\"Error: [Project] Merge Entity Error, [{\\\"message\\\":\\\"fail to reduce, DataRequest:d6463eb6-4be1-4258-80ed-46845888a225:20210915123037330\\\",\\\"stack\\\":\\\"Error: fail to reduce, DataRequest:d6463eb6-4be1-4258-80ed-46845888a225:20210915123037330\\\\n    at Object.mergeEntity (/home/app/node_modules/@fabric-es/fabric-cqrs/dist/queryHandler/createQueryDatabase.js:225:30)\\\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\\"}]\\n    at /home/app/node_modules/@fabric-es/fabric-cqrs/dist/utils/dispatcher.js:39:20\\n    at dispatch (/home/app/node_modules/redux/lib/redux.js:305:7)\\n    at /home/app/node_modules/redux-observable/lib/cjs/createEpicMiddleware.js:65:22\\n    at SafeSubscriber.dispatch [as _next] (/home/app/node_modules/redux/lib/redux.js:667:28)\\n    at SafeSubscriber.__tryOrUnsub (/home/app/node_modules/rxjs/internal/Subscriber.js:205:16)\\n    at SafeSubscriber.next (/home/app/node_modules/rxjs/internal/Subscriber.js:143:22)\\n    at Subscriber._next (/home/app/node_modules/rxjs/internal/Subscriber.js:89:26)\\n    at Subscriber.next (/home/app/node_modules/rxjs/internal/Subscriber.js:66:18)\\n    at MergeMapSubscriber.notifyNext (/home/app/node_modules/rxjs/internal/operators/mergeMap.js:93:26)\\n    at SimpleInnerSubscriber._next (/home/app/node_modules/rxjs/internal/innerSubscribe.js:27:21)\"}} ([query-handler] createQueryHandler.js)\n",
    "stream": "stdout",
    "kubernetes": {
        "pod_name": "gw-hktvmall-7d69859bfb-xvqjn",
        "namespace_name": "hktvmall",
        "pod_id": "52d7cb76-25b2-44b5-b705-8e3c1af02353",
        "host": "ip-192-168-171-4.ap-northeast-2.compute.internal",
        "container_name": "gw-hktvmall",
        "docker_id": "696aaf0e61e3a35e8f92451327c58f9dc2e3a0d6e621660209bcb9d3338c9de2",
        "container_hash": "hkiclming/cdi-consent-flow@sha256:db4d8366a0785b0c8c153e931011c0b332f1d531762fa09929e6a3217f093654",
        "container_image": "hkiclming/cdi-consent-flow:provider-beta.8"
    }
}

**Comment by rtang03** [comment]
Issue remains. Continue troubleshooting
