### ISSUE TITLE
when submitting tx, DefaultEventHandlerOptions timeout

### ISSUE THREAD

**Issue by icdhys** [rtang03/fabric-es#228]
When committing event to eventstore, there is timeout error thrown but the event is written to eventstore successfully.

Reason: default is 300s timeout. 

```
**Application Log:**
2021-09-16T13:29:40+08:00 [debug]: URL: "/pbc/order/confirm" ([relay] relayService.js)
2021-09-16T13:29:40+08:00 [debug]: HEADERS: {"authorization":"aaaaaaaaaaaa:aaaaaaaaaaaa","content-md5":"K3ZheN6GsVHC8hFIGNEiIQ==","date":"Thu, 16 Sep 2021 05:29:40 GMT","content-type":"application/json","content-length":"105","host":"uat2-relay11.fdi.hktfpcl.com","connection":"Keep-Alive","user-agent":"Apache-HttpClient/4.5.3 (Java/1.8.0_151)","cookie":"JSESSIONID=28C923C7BCE08D4589BC7E5E8E23415C","accept-encoding":"gzip,deflate"} ([relay] relayService.js)
2021-09-16T13:29:40+08:00 [debug]: PARAMS: [{"actionResponse":"A","comment":"Confirm PO","poId":"6837401441309573120","versionNo":1}] ([relay] relayService.js)
2021-09-16T13:29:40+08:00 [info]: ProxyReq Finish 1631770180791 ([relay] relayService.js)
2021-09-16T13:29:40+08:00 [debug]: [PERFTEST]{"id":"185cfd00e437b0995f12a9dd3650608c","url":"[object Object]","method":"POST","proxyReqStarts":1631770180789,"proxyReqFinish":1631770180791 ([relay] relayService.js)
2021-09-16T13:29:49+08:00 [info]: ProxyRes Starts 1631770189730 ([relay] relayService.js)
2021-09-16T13:29:49+08:00 [info]: Message processed with response 0 - '{"id":"185cfd00e437b0995f12a9dd3650608c","proxyReqStarts":1631770180789,"proxyReqFinish":1631770180791,"method":"POST","url":{"url":"/pbc/order/confirm","query":{}},"contentType":"application/json","proxyResStarts":1631770189730,"proxyResFinish":1631770189731,"statusCode":200,"statusMessage":""}' ([relay] relayService.js)
2021-09-16T13:29:49+08:00 [debug]: [PERFTEST]{"id":"185cfd00e437b0995f12a9dd3650608c","url":"/pbc/order/confirm","method":"POST","status":200,"proxyResStarts":1631770189730,"proxyResFinish":1631770189731} ([relay] relayService.js)
2021-09-16T13:29:49+08:00 [info]: ProxyRes Completed 1631770189732 ([relay] relayService.js)
2021-09-16T13:29:49+08:00 [debug]: [PERFTEST]{"sid":1631770189732-0,"count":1,"redisEventStart":1631770189833} ([sniffer] snifferSubscription.js)
2021-09-16T13:29:49+08:00 [debug]: [PERFTEST]{"id":"185cfd00e437b0995f12a9dd3650608c","sid":1631770189732-0,"redisResFinish":1631770189834} ([sniffer] snifferSubscription.js)
2021-09-16T13:29:49+08:00 [info]: [dispatcher] actionName: command_create, tx_id: f7Yzkw dispatched ([fabric-cqrs] createRepository.js)
2021-09-16T13:29:50+08:00 [debug]: gateway connected: myadmin ([fabric-cqrs] getNetwork.js)
2021-09-16T05:34:51.471Z - [33mwarn[39m: [TransactionEventHandler]: strategyFail: commit failure for transaction "46446f1665d6e8fcb42c6e5b51f4598746a9965fc510428f50705741a7268e12": TimeoutError: Event strategy not satisfied within the timeout period. No response received from peers: peer0-etc, peer1-etc
    at TransactionEventHandler.timeoutFail (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:125:23)
    at Timeout._onTimeout (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:112:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  transactionId: '46446f1665d6e8fcb42c6e5b51f4598746a9965fc510428f50705741a7268e12'
}
2021-09-16T05:34:51.472Z - [31merror[39m: [EventService]: unregisterEventListener[peer0-etc.cdi.uat:7051] - #11 - event listener was not found
Error: eventListener not found
    at EventService.unregisterEventListener (/home/app/node_modules/fabric-common/lib/EventService.js:750:11)
    at EventListener.unregisterEventListener (/home/app/node_modules/fabric-common/lib/EventListener.js:135:21)
    at CommitListenerSession.close (/home/app/node_modules/fabric-network/lib/impl/event/commitlistenersession.js:33:27)
    at Object.removeListener (/home/app/node_modules/fabric-network/lib/impl/event/listenersession.js:22:17)
    at NetworkImpl.removeCommitListener (/home/app/node_modules/fabric-network/lib/network.js:197:27)
    at TransactionEventHandler.cancelListening (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:81:22)
    at TransactionEventHandler.strategyFail (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:144:14)
    at TransactionEventHandler.timeoutFail (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:126:14)
    at Timeout.<anonymous> (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:112:18)
    at listOnTimeout (internal/timers.js:554:17)
2021-09-16T13:34:51+08:00 [error]: An uncaught error occurred! ([rl-etc] sniffer.js)
2021-09-16T13:34:51+08:00 [error]: Error: eventListener not found
    at EventService.unregisterEventListener (/home/app/node_modules/fabric-common/lib/EventService.js:750:11)
    at EventListener.unregisterEventListener (/home/app/node_modules/fabric-common/lib/EventListener.js:135:21)
    at CommitListenerSession.close (/home/app/node_modules/fabric-network/lib/impl/event/commitlistenersession.js:33:27)
    at Object.removeListener (/home/app/node_modules/fabric-network/lib/impl/event/listenersession.js:22:17)
    at NetworkImpl.removeCommitListener (/home/app/node_modules/fabric-network/lib/network.js:197:27)
    at TransactionEventHandler.cancelListening (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:81:22)
    at TransactionEventHandler.strategyFail (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:144:14)
    at TransactionEventHandler.timeoutFail (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:126:14)
    at Timeout.<anonymous> (/home/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:112:18)
    at listOnTimeout (internal/timers.js:554:17) ([rl-etc] sniffer.js)
2021-09-16T13:50:48+08:00 [info]: ProxyReq Starts 1631771448684 ([relay] relayService.js)
2021-09-16T13:50:48+08:00 [debug]: URL: "/pbc/invoices/receive" ([relay] relayService.js)
```

**Comment by rtang03** [comment]
I assert that is network issue. Close here, and will continue troubleshooting in the deployment repo
